### PR TITLE
This commit fixes the issues with WPF obfuscation. This issue arises …

### PR DESCRIPTION
**Pull request by nik-net**
…if the XAML file is nested under a folder within the root solution this change keeps the relative path of the XAML file intact while running the obfuscation engine. This is a particular issue with desktop applications that use Windows Forms and WPF together in a Visual Studio Tools for Office application. The way the .NET engine resolves the paths for XAML in this situation is based on the relative path which must remain intact.

### CODE REVIEW

**Comment by yck1509** [comment]
Thanks for your contribution!
However, it seems the tabs was converted to spaces. The main coding style of ConfuserEx uses tab. Would it be possible to convert the spaces to tabs?

**Comment by nik-net** [comment]
Hi Ki thanks for your note. Any chance you could point the file where this has happened so I can fix it? At my end it doesn't show me this problem.

Thanks.
Nik

**Comment by yck1509** [comment]
Hi,
You can go to the files changed tab. It shows that 'Confuser.Renamer/Analyzers/WPFAnalyzer.cs' and 'Confuser.Renamer/BAML/BAMLStringReference.cs' had their coding style changed.

**Comment by yck1509** [comment]
Or if you don't mind, I could fix it and apply it for you.

**Comment by nik-net** [comment]
I tried fixing Ki but I think its down to some nuances within my VIsual
Studio on Windows 10. If you don't mind could you fix this at your end? I
don't want to end up breaking something accidentally. Also if you fix this
would my contribution still show to the project in the github history?

**Comment by yck1509** [comment]
Sure, I'll check in your commit after fixing it, and you should remains as the author of the commit.

**Comment by yck1509** [comment]
Committed in 5fc7f8e33949e7c30d07db09e7c8810cb43d65a8.

**Comment by nik-net** [comment]
Thank you so much. Any chance you have a reference to a link or something that might explain why this happened and how can I fix it in future? Thanks.

**Comment by yck1509** [comment]
It is most likely caused by Visual Studio's auto-formatting. By default, VS uses spaces to indent and braces are in new lines. However, ConfuserEx project's coding style is using tabs to indent and braces in same line.
Usually when making contribution to projects, the new codes should remain consistent to the project code style. You could change the format settings of VS or try avoid triggering the auto-format when writing new code for other projects.

**Pull request closed without merging**
