### PR TITLE
Reversible renaming

### PR DESCRIPTION
**Pull request by picrap**
This is something that was present in Eazfuscator (that I'm divorcing with :smile:).
This idea is to create reversible name encryption (using a password and AES encryption).
This works as follows (using an attribute):
`[assembly: Obfuscation(Exclude = false, Feature = "preset(normal);`**`+rename(mode=reversible,password='`*`any password you like`*`');")]`**
I also did some changes in the GUI to decode from there.
And finally, there is a new class in `Confuser.Renamer` named `NameReverser` with a `Decode()` method (two overloads of it: static or instance method). Simply provider a stack trace and the encryption password and the method will decode it.

### CODE REVIEW

**Comment by picrap** [comment]
I also added some random padding bytes to the name before encryption, in order to make it look more random (which it is) after encryption.

**Comment by yck1509** [comment]
Thanks for your contribution! However, I would like to ask that is there anything that it satisfy while 'decodable' mode cannot? It seems to me both modes allows obfuscated name to be translated back to original name.

**Comment by picrap** [comment]
There are several reasons:
- my software is released to customers, and there are different versions at same time. Also, different builds can bring to same version, each one them being possibly deployed. So I can not keep track of decryption files
- error logs are uploaded automatically from client to server, and collected in an uniform way (I get all logs every day in a single file). Since they may come from different versions, I need a unique way to decrypt them.
This is why I suggested a reversible renaming :wink:

**Comment by picrap** [comment]
Glad to read from you, by the way. It's been three months without any activity, I was kind of worried... :frowning:

**Comment by yck1509** [comment]
Thanks for your concern! I understand the need of the mode now, however, personally I found the implementation not quite optimized. I'll write another one later. Thank you for suggestion!

**Comment by picrap** [comment]
As you like it! Also, if you write something on your own, it would be great to have a library to decipher names, to make it usable from other applications.

**Pull request closed without merging**
