### PR TITLE
Fix XML comments warning

### PR DESCRIPTION
**Pull request by caverna**
Just removing warning compilation messages

### CODE REVIEW

**Comment by yck1509** [comment]
Thanks for your contribution!
However, it seems some tabs was converted to spaces in 'DnlibUtils.cs' and 'Marker.cs'. Would it be possible to convert the spaces back to tabs?

**Comment by caverna** [comment]
I already asked this before...
I have this "issue" with some projects using tabs instead space...
Normally I don't touch VS configuration too much (just some shortcuts) to stay in "standard" way...
Looking at the net, I found [this guideline](https://msdn.microsoft.com/en-us/library/ff926074.aspx#Anchor_1) from MS of how to treat tabs.
I was a little curious, dispite MS guid, which one is "the preferable". I found (this project)[http://sideeffect.kr/popularconvention/#c#]. It reforces MS guide...
All my projects uses spaces instead tabs and I can't find a way to do this configuration "project based".
Do you know a way?

**Comment by caverna** [comment]
Ok, I used notepad++ to force the tab instead spaces...
Would you like some help to format all source code, clearing 'using', changing from tab to spaces and types (int, string, etc.) to 'var'?

**Comment by yck1509** [comment]
Thanks for the fix. There would be no need to cleanup other parts of code, as I would do it at a later time.

**Comment by yck1509** [comment]
In response to your question, I know that ReSharper could do project-based configuration. You can read https://stackoverflow.com/questions/1212092/visual-studio-per-solution-indentation-settings for some alternate ways.

**Pull request merged**
