### PR TITLE
SNK support

### PR DESCRIPTION
**Pull request by picrap**
The current version only seemed to support pfx files.
I added snk support (with a dirty patch hack, but found no other way to do this).

### CODE REVIEW

**Comment by yck1509** [comment]
Hi,
ConfuserEx supports SNK files. Is there anything not working for you?

**Comment by picrap** [comment]
I'm surprised, because it was failing (cryptographic exception). I can send you my snk by email if you want to test it.

**Comment by yck1509** [comment]
Please send it to confuser.net@gmail.com

**Comment by picrap** [comment]
The provided snk works without the patch (what went wrong when testing? I'll never know :cry:).
I close this useless pull request (and sorry for wasting your time).

**Pull request closed without merging**
