### PR TITLE
Update InvalidMetadataProtection.cs

### PR DESCRIPTION
**Pull request by XenocodeRCE**
Avoid UnConfuserEX to work by adding a new Heap (lol)

### CODE REVIEW

**Comment by Explicit-CB** [comment]
I assume the data array values can be changed and do not have to remain constant to what you have them set as?

**Comment by XenocodeRCE** [comment]
Yes but its size has to be exactely 16

**Comment by 3DotDev** [comment]
Maybe you would add a non static byte array like this : 

Guid.NewGuid.ToByteArray

**Comment by XenocodeRCE** [comment]
It would be nicer indeed

**Pull request merged**
